# Generated by Django 5.2.7 on 2025-10-26 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_coach'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='heigth',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='weigth',
            new_name='weight',
        ),
    ]
