# Generated by Django 5.2.7 on 2025-11-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_rename_heigth_pokemon_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pokemons/'),
        ),
    ]
