# Generated by Django 5.2.7 on 2025-11-10 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_pokemon_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('level', models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Coach',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='tipo',
            field=models.CharField(choices=[('L', 'Lagartija'), ('F', 'Fuego'), ('A', 'Agua'), ('P', 'Planta'), ('T', 'Tierra'), ('E', 'Eléctrico')], max_length=30),
        ),
    ]
