# Generated by Django 5.2.7 on 2025-11-10 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0005_trainer_delete_coach_alter_pokemon_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.trainer'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='tipo',
            field=models.CharField(choices=[('F', 'Fuego'), ('E', 'Eléctrico'), ('T', 'Tierra'), ('L', 'Lagartija'), ('A', 'Agua'), ('P', 'Planta')], max_length=30),
        ),
    ]
