# Generated by Django 5.2.7 on 2025-12-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0006_pokemon_trainer_alter_pokemon_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='trainers/'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='tipo',
            field=models.CharField(choices=[('E', 'Eléctrico'), ('P', 'Planta'), ('L', 'Lagartija'), ('T', 'Tierra'), ('F', 'Fuego'), ('A', 'Agua')], max_length=30),
        ),
    ]
